# Generated by Django 5.1.1 on 2024-12-02 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('cantidad_numeros', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('oculta', 'Oculta'), ('disponible', 'Disponible'), ('finalizada', 'Finalizada'), ('anulada', 'Anulada')], max_length=10)),
                ('imagen', models.ImageField(upload_to='rifas/')),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='premios/')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='App1.rifa')),
            ],
        ),
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('estado', models.CharField(default='reservado', max_length=10)),
                ('codigo_pago', models.CharField(blank=True, max_length=10, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.cliente')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros', to='App1.rifa')),
            ],
        ),
    ]
