# Generated by Django 5.1.1 on 2024-12-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numero',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='numero',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('pagado', 'Pagado')], default='disponible', max_length=10),
        ),
    ]
