# Generated by Django 5.1.1 on 2024-12-02 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_remove_numero_cliente_alter_numero_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeros_comprados', models.TextField()),
                ('codigo_pago', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.cliente')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.rifa')),
            ],
        ),
    ]
