# Generated by Django 5.1.3 on 2024-12-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_ganador'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='numero',
            unique_together={('rifa', 'numero')},
        ),
    ]
