# Generated by Django 5.1.3 on 2024-12-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_alter_numero_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='numeros_comprados',
        ),
        migrations.AddField(
            model_name='compra',
            name='numeros_comprados',
            field=models.ManyToManyField(to='App1.numero'),
        ),
    ]
